### ISSUE TITLE
Workaround for network-operation?

### ISSUE THREAD

**Issue by aiwenxu** [brian-team/brian2genn#123]
Hi! I have some code with a `network-operation` that works in brian2. However, I cannot think of a way to rewrite it so that I can run it via brian2genn. 

A simplified version of my problem is as follows. Suppose we have two groups of neurons.
```
eqs = '''
dV/dt = G_syn/tau : volt
G_syn : siemens
'''
g1 = NeuronGroup(2, eqs)
g2 = NeuronGroup(3, eqs)
```
We also have pairwise distances between the two groups of neurons. 
```
distances = np.array([[1,2,3],[4,5,6]])
```
Now the `G_syn` here depends on the membrane voltage of the neurons in the other group with a constant delay and the distances. For example, for the first neuron in `g1`, G_syn(t) = V21(t-1)exp(-1) + V22(t-1)exp(-2) + V23(t-1)exp(-3), where V21, V22 and V23 are the voltages of the first, second and third neuron in `g2` respectively.

Previously I was using a `network-operation` to update `G_syn` at every time step, but it obviously wouldn't work with brian2genn. 

 I am new to brian2 and also neuroscience to be honest, so I might be overlooking some simple things. I hope this makes sense and thanks in advance!

**Comment by kernfel** [comment]
I'm not sure I understand what you're trying to do; it might help to see what the network-operation looks like. From what I gather, this is not supposed to be event-driven, right? Could you use a clock-driven `Synapses` model, for example? I'm not sure if that'll play nice with delays though...

**Comment by aiwenxu** [comment]
Thanks for your reply! What I am trying to do is to update `G_syn`  according to the membrane voltages of the other `NeuronGroup` (delayed by 1 ms) and predefined pairwise distances between the two `NeuronGroup`s. The following is the code. My apologies if it is confusing.

```
# a function that calculates the contribution of V_presynaptic into G_syn
def g_syn_t(g_min, g_max, V_50, beta, increasing, V_presynaptic):
    V_presynaptic = V_presynaptic / mV
    if increasing:
        return g_min + (g_max-g_min) * (1-1/(1+np.exp((V_presynaptic-V_50)/beta)))
    else:
        return g_min + (g_max-g_min) * (1/(1+np.exp((V_presynaptic-V_50)/beta)))

# a function that calculates the contribution of the distances into G_syn
def G_syn_t(dist_mat, sigma, g_min, g_max, V_50, beta, increasing, V_presynaptic):
    W = np.sum(np.exp(-dist_mat/sigma), axis=1)
    dist_w = np.exp(-dist_mat/sigma)
    g_syn = g_syn_t(g_min, g_max, V_50, beta, increasing, V_presynaptic)
    result = np.dot(dist_w, g_syn)
    result = (1/W) * result
    result = np.transpose(result)
    return result * nS

# cr and hrz are NeuronGroups. I use StateMonitors to get the voltages 1 ms ago to do the calculation,
# and update G_syn in cr and hrz.
@network_operation
def update_G_syn(t):
        
    V_h = np.ones(NUM_HRZ) * (hrz_E_rest) if t < 1*ms else (hrz_mon.V[:, len(hrz_mon.V[0])-10])
    cr.G_syn = G_syn_t(cr_hrz_dist_mat, 2.5, 0.0, 3.0, -29.5, 7.4, True, V_h)
    
    V_cr = np.ones(NUM_CR) * (cr_E_rest) if t < 1*ms else (cr_mon.V[:, len(cr_mon.V[0])-10])
    hrz.G_syn = G_syn_t(hrz_cr_dist_mat, 7.0, 0.0, 7.0, -43.0, 2.0, True, V_cr)
```

I went with your suggestion and I think I have a working version where I am using `Synapses` to implement this mechanism. But to run it with brian2genn I at least see two problems.
1. brian2genn reports that "brian2genn does not support references to pre-synaptic variables in on_pre statements".
2. I am also using a custom schedule: `SynpaticPathway`s are set at "start" and `StateMonitor`s are set at "before_resets". But custom schedules are listed in the unsupported features.

Do you see any workarounds for those two problem? Or any other ideas are much appreciated.

**Comment by kernfel** [comment]
Thank you for the details. This looks like gap junctions to me, so I've tried running the [Brian2 gap junction example](https://brian2.readthedocs.io/en/stable/examples/synapses.gapjunctions.html) in Brian2GeNN. This works without any issues and could be extended straightforwardly to your problem, I think, except that it isn't delayed. I'm not sure there's a way to get around that, short of manually adding a delay buffer of sorts, which should be possible in principle (assuming you're integrating at 0.1ms, and the delay is uniformly 1ms), but also a bit messy.

Perhaps @tnowotny knows of a way to make delayed gap junctions?

**Comment by tnowotny** [comment]
@kernfel is right, I think. Regarding delays, that is probably not possible but I may be missing something, let's also get a quick opinion from @mstimberg ...
And relatedly, @neworderofjamie, would GeNN support delays for accessing a pre-synaptic variable within synapse dynamics?

**Comment by neworderofjamie** [comment]
This is well above the level of my Brian modelling knowledge but synapse dynamics can indeed access presynaptic variables with a fixed axonal delay

**Comment by tnowotny** [comment]
I *think* setting a delay then might just work. From the gap-junction example - modified with a delay of 1 ms:
```
S = Synapses(neurons, neurons, '''
             w : 1 # gap junction conductance
             Igap_post = w * (v_pre - v_post) : 1 (summed)
             ''', delay=1*ms)
```
(sorry haven't tested it myself but give it a go?)

**Comment by mstimberg** [comment]
Hi everyone. This is actually not a Brian2GeNN issue, Brian itself does not support continuous interactions with delays. If you set a delay (as in @tnowotny's comment above), this will be a delay for what we call the synaptic *pathway*, i.e. the spike-triggered events. For a continuous interaction we'd have to have a data structure that continously stores all values for the delay period, and we don't have this yet. For reference: brian-team/brian2#467 and our [recent discussion on the Brian forum](https://brian.discourse.group/t/adding-delay-differential-equation-solver/191).

**Comment by tnowotny** [comment]
Oh ... that is interesting; as I remember it, the summed variable code above will go into GeNN synapse_dynamics code and (as @neworderofjamie confirmed) a reference to $(Vpre) would inadvertently be served with a global axonal delay (*if* the synaptic delay above is indeed translated into a GeNN axonal delay as I believe it is).
We might have a potential small inconsistency between Brian 2 and Brian2GeNN behaviour ... but I could be wrong.

**Comment by kernfel** [comment]
At the moment, this is only a _potential_ inconsistency, which can't appear in practice. The reason being that Brian won't allow your suggested Synapses initialisation, on the basis that there is no synaptic pathway to apply the delay to. If, on the other hand, a dummy on_pre argument is provided, this will run as expected (meaning: with no delay on the synapse `model` equations) in standard Brian, but will fail in Brian2GeNN on the basis that multiple pathways are not implemented.

**Comment by kernfel** [comment]
I guess for @aiwenxu this is beside the point, though. My suggested implementation won't work, except with ~~ugly hacks~~ elegant ways around the missing delay feature. Could code in `run_regularly` operations access recorded voltages? Not that you'd want to do that either if you're looking for something that performs well...

**Comment by mstimberg** [comment]
No, unfortunately the only way to have a real continuous interaction with delays in Brian right now is to have some manual workaround, either with a `network_operation` or with a custom function. Actually the latter might work, by wrapping it in a `run_regularly` call and storing it in some variable. Let me see whether I can put together a simple example.

**Comment by mstimberg** [comment]
Ok here is the promised example, losely based on the code in the original post:
```Python
tau = 10*ms
g1 = NeuronGroup(2, '''V : volt
                       t_start : second (constant)
                       t_stop  : second (constant)
                       V_delayed : volt''')
g1.t_start = [10, 20]*ms
g1.t_stop  = [30, 40]*ms
g1.run_regularly('V = 10*mV*int(t>=t_start and t<=t_stop)')
g1.run_regularly('V_delayed = get_delayed(i, timestep(t-5*ms, dt))')

eqs = '''
dV/dt = G_syn/tau : volt
G_syn : volt
'''
g2 = NeuronGroup(3, eqs)

distances = np.array([[1, 1.5, 2.],
                       [2.5, 3., 3.5]])

syn = Synapses(g1, g2, '''w : 1
                          G_syn_post = V_delayed_pre*exp(-w) : volt (summed)''')
syn.connect()
syn.w = distances.flat

g1_mon = StateMonitor(g1, ['V', 'V_delayed'], record=True)
g2_mon = StateMonitor(g2, 'V', record=True)


@implementation('cpp', '''
float get_delayed(int index, int step) {
    step = max(0, step);  // do not go beyond start
    if (brian::ARRAY_NAME.n > 0) { // any data?
        return brian::ARRAY_NAME(step, index);
    } else {
        return 0.0;
    }
}
'''.replace('ARRAY_NAME',
            device.get_array_name(g1_mon.variables['V'],
                                  access_data=False)))
@declare_types(index='integer', step='integer')
@check_units(index=1, step=1, result=volt)
def get_delayed(index, step):
    raise NotImplementedError('Use C++ target')

run(100*ms)
fig, ax = plt.subplots(3, 1, sharex=True, sharey=True)
ax[0].plot(g1_mon.t/ms, g1_mon.V.T/mV)
ax[0].set_ylabel('g1.V (mV)')
ax[1].plot(g1_mon.t/ms, g1_mon.V_delayed.T/mV)
ax[1].set_ylabel('g1.V_delayed (mV)')
ax[2].plot(g2_mon.t/ms, g2_mon.V.T/mV)
ax[2].set(xlabel='t (ms)', ylabel='g2.V (mV)')
fig.show()
```
This accesses the underlying data structure that stores the data for the `StateMonitor` recording `V` from `g1`. The details are a bit tricky, the current code will actually use one timestep more delay than what is specified (note that I used 5ms instead of 1ms just to make the delay a bit more obvious). The reason is that in Brian2GeNN, we cannot flexibly order the operations as we could do in Brian 2. The `run_regularly` operations will always be executed before the monitored recordings, so we are actually accessing the monitored values from the previous time steps. This also leads to the need for the `if` in the C++ code, because in the very first time step there is nothing in the monitor yet.

I changed the model of the first group a bit to have to different step currents for the two neurons, but this is obviously just for demonstration, `V` could be described by a differential equation. The code should work for both C++ standalone and Brian2GeNN, let me know if anything is unclear!

**Comment by aiwenxu** [comment]
Thank you all so much for your help! I think this example solves my problem perfectly. I have two follow-up questions.

1. I have the following code for `Synapses`:
```
D : 1
W : 1
G_syn_post = (1/W) * (0.0*nsiemens + (7.0-0.0)*nsiemens * (1-1/(1+exp((V_delayed_pre-(-43*mV))/(2.0*mV))))) * exp(-D/10.5) : siemens (summed)
```
But brian2genn reports the following errors:
```
/home/aiwenxu/retina-model-Cottaris/GeNNworkspace/magicnetwork_model_CODE/synapseUpdate.cc(36): error: identifier "nsiemens" is undefined

/home/aiwenxu/retina-model-Cottaris/GeNNworkspace/magicnetwork_model_CODE/synapseUpdate.cc(36): error: identifier "mV" is undefined

/home/aiwenxu/retina-model-Cottaris/GeNNworkspace/magicnetwork_model_CODE/synapseUpdate.cc(47): error: identifier "nsiemens" is undefined

/home/aiwenxu/retina-model-Cottaris/GeNNworkspace/magicnetwork_model_CODE/synapseUpdate.cc(47): error: identifier "mV" is undefined
```
I can rewrite the equations so that they are dimensionless, but I am just wondering if there is a way to keep the equations as they are. 

2. Is there a way to rewrite `get_delayed` so that it works for all `NeuronGroup`s? Something like:
```
def get_delayed(index, step, neuron_group)
```

**Comment by mstimberg** [comment]
> I can rewrite the equations so that they are dimensionless, but I am just wondering if there is a way to keep the equations as they are.

Oh, that appears to be a bug in Brian2GeNN... The fix seems to be trivial, replacing line
https://github.com/brian-team/brian2genn/blob/f19770bedd16144594d44d1dcaa69e3e02308c98/brian2genn/device.py#L1458
by
```Python
                    for k,v in iteritems(codeobj.variables):
```
I'm running some tests and will then upload the fix.

>     Is there a way to rewrite `get_delayed` so that it works for all `NeuronGroup`s?

The `get_delayed` function has the name of the monitored variable (which includes the name of the `NeuronGroup`) hardcoded, so it can only be used for a single group. I could imagine some ugly hack to get it working with several groups (or you could of course have one function per group), but maybe first make sure that you actually need several `NeuronGroup`s. If your groups share the same equations, they can all be implemented in a single group and you can use [subgroups](https://brian2.readthedocs.io/en/stable/user/models.html#subgroups) to split this group up.

**Comment by aiwenxu** [comment]
That makes sense. Thanks a lot!!!

**Comment by aiwenxu** [comment]
I followed your suggestion and implemented my model via subgroups, but I have the following error.

```
NotImplementedError: brian2genn does not support summed variables when the target is a Subgroup.
```

I am just wondering if this is a feature that will be implemented anytime soon. Thanks!

**Comment by mstimberg** [comment]
Oh, sorry I did not think of this restriction. I don't quite remember why we have this actually, I'll have a look tomorrow. The restriction might be easy to remove.

**Comment by mstimberg** [comment]
I had a look and unfortunately the restriction seems not to be that straightforward to remove, see https://github.com/brian-team/brian2genn/pull/87#issuecomment-489167834 . So you'll have use the summed variable with the full group which should be possible in general. You'll might have to introduce new variables in the target group to workaround the limitation that only a single `(summed)` expression is allowed for each target variable. But maybe you can do everything with a single `Synapses` object as well (which would also be more efficient than having separate objects)? Hard to say without knowing more about your model.

**Comment by aiwenxu** [comment]
Ok thanks! I think I will probably implement my model with several `NeuronGroup`s. There are a couple of connections that are governed by the same equations albeit with different parameters, so those can be implemented in a single `Synapses` object. I will play with it a bit more.

**Comment by aiwenxu** [comment]
I think I got it fully working, so I am going to close this issue. Thanks again everyone!

**Comment by aiwenxu** [comment]
Hello again! I am wondering if it is possible to modify the function `get_delayed` so that it can be run on the CPU. My fairly large network has been quite different from run to run (possibly due to scheduling on the GPU), so I would like to do a sanity check by running the network on the CPU. Thanks!

**Comment by kernfel** [comment]
I don't think you need to change anything in the function itself, since it's a CPP implementation. You can get it to run on the CPU though, either by using the cpp backend in native Brian2 (with `set_device('cpp_standalone')`), or, probably more sensibly, by getting Brian2GeNN to not use the GPU (with `set_device('genn', use_GPU=False)`).

**Comment by aiwenxu** [comment]
Yes, thank you!!! I should have read the documentation more carefully.

**Comment by aiwenxu** [comment]
Hi there, me again. I am wondering if the seed() function in brian2 translates correctly to the corresponding function in GeNN? Thanks!

**Comment by mstimberg** [comment]
I think using the `seed` function in `brian2genn` currently raises a `NotImplementedError`, so I think it is unsupported at the moment ;) I'm not quite sure how much work is needed to get this working – @neworderofjamie / @tnowotny : GeNN now provides support for something like Random123, doesn't it? IIRC, in brian2genn we are still using a simple LCG method, right?

**Comment by neworderofjamie** [comment]
Brian2GeNN does indeed just implement a simple LCG. Removing that and replacing it with GeNN's built in RNG is hopefully one of the things our GSoC student is going to work on this summer.

**Comment by mstimberg** [comment]
> Brian2GeNN does indeed just implement a simple LCG.

Thanks for confirming. In principle we could set the seed for the LCG, but it wouldn't help much since it depends on the order of execution on the GPU, right?

> Removing that and replacing it with GeNN's built in RNG is hopefully one of the things our GSoC student is going to work on this summer.

That would be great, fingers crossed that it works out!

**Comment by neworderofjamie** [comment]
I _think_ there's an LCG per thread (@tnowotny?) so setting their seed should also work,

**Comment by neworderofjamie** [comment]
(although, non-deterministic order of execution will mean that, in some circumstances, the same seed will not result in identical results)

**Comment by tnowotny** [comment]
> I _think_ there's an LCG per thread (@tnowotny?) so setting their seed should also work,

Yes, I think so. That of course implies that the correct number of seeds would have to be provided ... but essentially, it is probably not possible to construct something where using seed() with different backends gets you the same results.
