### ISSUE TITLE
StateMonitor fails to collect data from some Synapses

### ISSUE THREAD

**Issue by kernfel** [brian-team/brian2genn#136]
Disclaimer: I'm not entirely sure whether this is an issue with Brian2GeNN or whether I'm misunderstanding how to correctly specify synapse indices for StateMonitors, please bear with me.

I'm trying to monitor state variables of a number of `Synapses` objects, all of which connect between subgroups of a single `NeuronGroup`. While this is no problem in numpy or standalone mode, some monitors turn up empty in genn mode. In particular, it seems to be that synapses originating from subgroups with a non-zero offset are affected.

In contrast to synapses, monitoring values on the subgroups themselves is not affected.

Specs:
brian2genn, current master (17b6d61)
brian2, 2.4.2
genn 4.6.0 (037af10)

Exhaustive demonstration follows.

```python
import numpy as np
from brian2 import *
import brian2genn

# Comment this out for correct results:
set_device('genn')

defaultclock.dt = 1 * ms
N = 3

G = NeuronGroup(N, 'v: 1', threshold='t == i * ms')
G.v = 0

net = Network(G)

# Create all possible (contiguous) subgroups
subgroups = {}
for offset in range(N):
    for size in range(1, N-offset+1):
        subgroups[f'off{offset}size{size}'] = (size, G[offset:offset+size])

eqs_synapse = 'w: 1'
on_pre = '''
w += 1
v_post += 1
'''

# Connect and monitor all subgroups pairwise
synapses = {}
monitors = {}
vmonitors = {}
for key_pre, (npre, gpre) in subgroups.items():
    for key_post, (npost, gpost) in subgroups.items():
        key = f'{key_pre}_{key_post}'

        synapses[key] = Synapses(
            gpre, gpost, eqs_synapse, on_pre=on_pre, name=key)
        synapses[key].connect()
        net.add(synapses[key])

        monitors[key] = StateMonitor(
            synapses[key], 'w', record=range(npre*npost), name=f'{key}_monitor')
        net.add(monitors[key])

    vmonitors[key_pre] = StateMonitor(
        gpre, 'v', record=range(npre), name=f'{key_pre}_monitor')
    net.add(vmonitors[key_pre])

# Run
net.run((N+2) * ms)

for key, monitor in monitors.items():
    print(key, np.all(synapses[key].w == monitor.w[:, -1]))
    print(monitor.w)

for key, monitor in vmonitors.items():
    print(key, monitor.v, sep='\n')
```

**Comment by tnowotny** [comment]
I have been able to reproduce the problem and Jamie and I were able to identify the root cause. I will work on a fix this afternoon.

**Comment by tnowotny** [comment]
@kernfel ... please try the fix_synapses_subgroup_monitors branch and check that it indeed resolves your issue.
There seems to be a separate issue with brian 2 >= 2.5.x so I am not sure when we will be able to merge this fix.
Thanks a lot for a well-documented bug report.

**Comment by kernfel** [comment]
Thank you very much for the quick turnaround! This solved the issue.
