### ISSUE TITLE
[Feature request] Support for slower clocks in Monitors

### ISSUE THREAD

**Issue by kernfel** [brian-team/brian2genn#139]
Since the output of any Monitor activity necessarily ends up in host memory and does not affect model evaluations, I feel it should be possible to provide slower clocks for these, with dt a multiple of the model clock. I don't have the time right now to dig into the code here, but would appreciate any pointers as to (a) whether this is a sensible and reasonably implementable request, and (b) if so, where to start to add such support.

Alternatively, smart workarounds to doing regular, but infrequent state monitoring during a long run would be an acceptable resolution, too. :)

Best, Felix

**Comment by tnowotny** [comment]
I think, given the way state monitors are currently implemented in brian2genn it would not be difficult to add support for slower clocks (if multiples of the model clock).
The obvious strategy in my mind would be to add a check here:
https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/device.py#L1615
whether the state monitor has a clock differing from the model clock pretty much doing the exact same as for general run_regularly objects, which already support slower clocks. In other words pretty much exactly this code:
https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/device.py#L1682-L1704
... and add a ```step``` property to stateMonitorModel (https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/device.py#L282)
that holds the calculated value for how many steps to wait for the next update.
Then one can just bracket all the updates in ```run_reg_state_monitor_operations``` here: https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/templates/engine.cpp#L86-L183
by the line 
https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/templates/engine.cpp#L120
and not only the "proper" run_regularly operations as currently. 
Similarly, the test for i%step == 0 should be used in the second block https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/templates/engine.cpp#L242-L261
which covers the case where the state monitor is recording at the end of the timestep.

I think that should be all that's required.
I thought there also might be a check for state monitor models using a different clock and a NotImplementedError thrown but I did not see it just now. If there is, that would need to be removed obviously.

**Comment by mstimberg** [comment]
I was about to reply, but @tnowotny beat me to it :-) I agree with everything he wrote, and I also agree that it would be useful and not that difficult to implement.


> I thought there also might be a check for state monitor models using a different clock and a NotImplementedError thrown but I did not see it just now. If there is, that would need to be removed obviously.

`StateMonitor` would have to be included as an exception for the generic "multiple clock" check here:
https://github.com/brian-team/brian2genn/blob/17b6d61d363b11d1823009d4d813a5823aea10dd/brian2genn/device.py#L1807-L1810

**Comment by kernfel** [comment]
Cool, thank you both! I'll have a go at this soon.
