### ISSUE TITLE
mod function

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#19]
there are some problems around using fmod with integer arguments and MSVC compiler. Dan and Marcel made a hack with universal support code defining all kinds of overloads for _brian_mod.
I have for now just re-translated _brian_mod to fmod. Needs testing whether this causes problems or nvcc is fine with it on all platforms.

**Comment by mstimberg** [comment]
Hi Thomas. Is this change in the development branch or is this a temporary hack you are using on your own machine? brian2genn does not seem to work with current master because it still expects a mod function in `DEFAULT_FUNCTIONS`.

**Comment by mstimberg** [comment]
Uh, I just realized we already had this open issue... I'll close this here as it is superceded by #43.
