### ISSUE TITLE
Errors when using the brian2genn interface

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2genn#21]
_From @Kwartke on August 24, 2015 12:58_

When running the attached code (adapted from tests/features/speed.py) using the brian2genn interface, the compilation fails.
Recent and clean versions of brian2 (master branch), brian2genn (develop branch) and genn (master branch) from the respective git repositories were used.
When running the attached examples (HHNeuronsOnly and CUBAFixedConnectivity): the following compiler errors show up (the compiler errors are the same for both examples but differ when using different cuda versions):

on a GTX Titan Black (CUDA 6.5):
```
magicnetwork_model.cc: error: ‘struct neuronModel’ has no member named ‘supportCode’
   n.supportCode= tS("\n\
     ^
```

on a GTX 580 (CUDA 7.0):
```
  File "p.py", line 36, in <module>
    group.v = El
...
File "/home/wartke/brian2genn/brian2genn/device.py", line 150, in code_object_class
    raise ValueError("Cannot specify codeobj_class for GeNN device.")
ValueError: Cannot specify codeobj_class for GeNN device.
```

Our aim is to run all examples from tests/features/speed.py using brian2genn. However, errors similar as those above show up for the other examples as well. 

Kind regards, Konrad Wartke & Moritz Augustin

___________________
attached example no. 1: 
___________________
```Python
from brian2 import *
import brian2genn

set_device("genn")
num_neurons = 10
# Parameters
area = 20000 * umetre**2
Cm = 1 * ufarad * cm**-2 * area
gl = 5e-5 * siemens * cm**-2 * area
El = -65 * mV
EK = -90 * mV
ENa = 50 * mV
g_na = 100 * msiemens * cm**-2 * area
g_kd = 30 * msiemens * cm**-2 * area
VT = -63 * mV
        # The model
eqs = Equations('''
        dv/dt = (gl*(El-v) - g_na*(m*m*m)*h*(v-ENa) - g_kd*(n*n*n*n)*(v-EK) + I)/Cm : volt
        dm/dt = 0.32*(mV**-1)*(13.*mV-v+VT)/
            (exp((13.*mV-v+VT)/(4.*mV))-1.)/ms*(1-m)-0.28*(mV**-1)*(v-VT-40.*mV)/
            (exp((v-VT-40.*mV)/(5.*mV))-1.)/ms*m : 1
        dn/dt = 0.032*(mV**-1)*(15.*mV-v+VT)/
            (exp((15.*mV-v+VT)/(5.*mV))-1.)/ms*(1.-n)-.5*exp((10.*mV-v+VT)/(40.*mV))/ms*n : 1
        dh/dt = 0.128*exp((17.*mV-v+VT)/(18.*mV))/ms*(1.-h)-4./(1+exp((40.*mV-v+VT)/(5.*mV)))/ms*h : 1
        I : amp
        ''')
        # Threshold and refractoriness are only used for spike counting
group = NeuronGroup(num_neurons, eqs,
                            threshold='v > -40*mV',
                            refractory='v > -40*mV')
group.v = El
group.I = '0.7*nA * i / num_neurons'
run(1*second)
device.build(directory="genn", compile=True, run=True)
```
___________________
attached example no. 2: 
___________________
```Python
from brian2 import *
import brian2genn

set_device("genn")
N = 10
Ne = int(.8 * N)
taum = 20 * ms
taue = 5 * ms
taui = 10 * ms
Vt = -50 * mV
Vr = -60 * mV
El = -49 * mV
eqs = '''
        dv/dt  = (ge+gi-(v-El))/taum : volt (unless refractory)
        dge/dt = -ge/taue : volt (unless refractory)
        dgi/dt = -gi/taui : volt (unless refractory)
        '''
P = NeuronGroup(
            N, eqs, threshold='v>Vt', reset='v = Vr', refractory=5 * ms)
P.v = 'Vr + rand() * (Vt - Vr)'
P.ge = 0 * mV
P.gi = 0 * mV
we = (60 * 0.27 / 10) * mV  # excitatory synaptic weight (voltage)
wi = (-20 * 4.5 / 10) * mV  # inhibitory synaptic weight
Ce = Synapses(P, P, pre='ge += we')
Ci = Synapses(P, P, pre='gi += wi')
Ce.connect('i<Ne', p=80. / N)
Ci.connect('i>=Ne', p=80. / N)
s_mon = SpikeMonitor(P)
run(1*second)
device.build(directory="genn2", compile=True, run=True)
```

_Copied from original issue: brian-team/brian2#545_

**Comment by mstimberg** [comment]
_From @Kwartke on August 24, 2015 13:54_

First we missed the right repository for this issue (apologize). Maybe one could move this issue to brian-team/brian2genn as it fits better there...

Additionally we forgot to mention, that due to issue #19 of brian2genn we removed ('mod', 'fmod') in the function name translation of brian2genn/genn_generator.py to allow code generation. 

To complete the initial issue report: the first error we describe above shows up when -- after the brian device.build call fails -- we manually execute "cd genn ; buildmodel.sh magicnetwork_model". This command yields then the full error:

[wartke@asterope genn]$ buildmodel.sh magicnetwork_model 
model path: /home/wartke/genn
model name: magicnetwork_model
rm -rf obj bin/generateALL
mkdir -p obj
g++ -DNVCC=\"/opt/cuda/bin/nvcc\" -include /home/wartke/genn/magicnetwork_model.cc -I/opt/cuda/include -I/home/wartke/genn-git/lib/include -I/home/wartke/genn-git/userproject/include src/generateALL.cc -o obj/generateALL.o -c
In file included from <command-line>:0:0:
/home/wartke/genn/magicnetwork_model.cc: In function ‘void modelDefinition(NNmodel&)’:
/home/wartke/genn/magicnetwork_model.cc:55:3: error: ‘GENN_PREFERENCES’ has not been declared
   GENN_PREFERENCES::autoRefractory= 0;
   ^
/home/wartke/genn/magicnetwork_model.cc:105:5: error: ‘struct neuronModel’ has no member named ‘supportCode’
   n.supportCode= tS("\n\
     ^
GNUmakefile:51: recipe for target 'obj/generateALL.o' failed
make: *** [obj/generateALL.o] Error 1
/home/wartke/genn-git/lib/bin/buildmodel.sh: line 26: bin/generateALL: No such file or directory
Model build complete ...

**Comment by mstimberg** [comment]
Hi, `brian2genn` development is synchronized with `genn` development, so you'll also need the `develop` branch for genn itself. But it seems that in addition there is something missing in the current state of the `brian2genn` repository, maybe Thomas did not push something. I'll move the issue over to the brian2genn repository, then Thomas can comment (but in general note that `brian2genn` is under heavy development, so it's expected that it breaks from time to time).

**Comment by tnowotny** [comment]
Hi, the error you're experiencing looks like you are using the latest GeNN release (or, equivalently the master branch). Brian2genn is undergoing rapid development at the moment and is synchronised with the GeNN development branch (which is also rapidly changing). 
I have just committed and pushed the very latest versions on each before commenting here.

**Comment by mstimberg** [comment]
Hi Thomas, there still seems to be something missing in the `brian2genn` repository, e.g. the `models.cc` template refers (in line 120) to `neuron_model.hash_code_lines` which should probably be `neuron_model.hashdefine_lines` and to `synapse_model.postsyn_pvalue` (line 49) which does not exist in brian2genn's `synapseModel` class.

**Comment by moritzaugustin** [comment]
thanks for the fast replies! the two simple examples (which were described above by @kwartke via @mstimberg) now do run through at my machine  :-)
to assess the correctness of the genn simulations I applied the genn device of brian2genn to a couple of further (standard brian2) examples for which I describe the results and further issues below:

example 1: IF_curve_Hodgkin_Huxley.py
the simulation runs through but the results with brian2genn differ from those obtained using the non-standalone brian (left: brian2 cpp_standalone; right: brian2genn -- note the axis scaling)
![brian_vs_brian2genn_-_if_curve_hh](https://cloud.githubusercontent.com/assets/4638480/9443723/f77370ac-4a82-11e5-83f3-a20fb826abd6.png)

problem 2: CUBA.py
the compilation runs through but during runtime an out of memory error shows up. output:
['./runner', 'test', '1.0', '1']
# DT 0.000100 
# totalTime 1.000000 
magicnetwork_model_CODE/runner.cc: 55: cuda error 2: out of memory

problem 3: COBAHH.py (similar error for STDP_standalone.py)
here an error (similar to what @mstimberg reported) appears at the stage of compilation. output:
call was bin/generateALL /home/augustin/Projects/Brian2/github/brian-team_brian2genn/examples_brian2/COBAHH_genn 
neuron group neurongroup_subgroup not found, aborting ... 
buildmodel Error: exiting with status 1
rm -rf runner *.o *.dSYM/
/opt/cuda/bin/nvcc   --compiler-options "-O3" -I. -I/opt/cuda/include -I/opt/cuda/samples/common/inc -I/home/augustin/Projects/Brian2/github/genn-team_genn/lib/include -I/home/augustin/Projects/Brian2/github/genn-team_genn/userproject/include  runner.cu -o runner.o -c
runner.cu:10:45: fatal error: magicnetwork_model_CODE/runner.cc: No such file or directory
compilation terminated.

**Comment by mstimberg** [comment]
[just a minor remark, please wrap output/code blocks in ``` (triple back ticks), otherwise they are very hard to read]

**Comment by tnowotny** [comment]
oh well ... more stuff to look at. The out of memory error is probably due to using dense matrix implementations. You can try to set the just introduced preference devices.genn.connectivity='SPARSE' which may help. I am working on debugging things around support code at the moment but will return to these later.

**Comment by moritzaugustin** [comment]
```
prefs.devices.genn.connectivity='SPARSE'
``` 
indeed solves problem 2 :+1:

**Comment by tnowotny** [comment]
in response to Marcel:
1. "models.cc template refers (in line 120) to neuron_model.hash_code_lines which should probably be neuron_model.hashdefine_lines"
This was a left-over from experimenting. There is actually no such thing as separate hash code lines. I have fixed this by removing the reference from the template

2. " and to synapse_model.postsyn_pvalue (line 49) which does not exist in brian2genn's synapseModel class."
Similar - I originally didn't realise that GeNN postsyn models would be minimal and always parameter-less in brian2genn. I have fixed this in the latest commit.

**Comment by tnowotny** [comment]
Ok, the COBAHH example fails because it is using neuron subgroups (Pe, Pi) which is not supported in brian2genn. If you rephrase it like this:
```Pe = NeuronGroup(3200, model=eqs, threshold='v>-20*mV', refractory=3*ms,
                method='exponential_euler')
Pi = NeuronGroup(800, model=eqs, threshold='v>-20*mV', refractory=3*ms,
                method='exponential_euler')
Ce = Synapses(Pe, Pe, pre='ge+=we', connect='rand()<0.02')
Ce2 = Synapses(Pe, Pi, pre='ge+=we', connect='rand()<0.02')
Ci = Synapses(Pi, Pe, pre='gi+=wi', connect='rand()<0.02')
Ci2 = Synapses(Pi, Pi, pre='gi+=wi', connect='rand()<0.02')

# Initialization
Pe.v = 'El + (randn() * 5 - 5)*mV'
Pe.ge = '(randn() * 1.5 + 4) * 10.*nS'
Pe.gi = '(randn() * 12 + 20) * 10.*nS'
Pi.v = 'El + (randn() * 5 - 5)*mV'
Pi.ge = '(randn() * 1.5 + 4) * 10.*nS'
Pi.gi = '(randn() * 12 + 20) * 10.*nS'

# Record a few traces
trace = StateMonitor(Pe, 'v', record=[1, 10, 100])
```
then it runs fine and gives some results (would need to be determined whether the results are "the same").
I need to find a way to raise a NotImplementedError for subgroups. (or implement them for that matter).

**Comment by tnowotny** [comment]
Other than that brian2genn does not support sub-groups all problems introduced in this issue have now been fixed so I will close it.
