### ISSUE TITLE
Brian2GeNN not up to date with brian2 master

### ISSUE THREAD

**Issue by Kwartke** [brian-team/brian2genn#25]
When using the brian2genn interface (current develop branch) together with genn (current development branch) there were several problems related to code changes in Brian2.

For example: the class AttributeVariable does not exist anymore, the main_queue has sometimes an additional parameter, there were some changes to the clock structure, ...

Since we (@moritzaugustin and @kwartke) want to benchmark our CUDA implementation against the GeNN simulator, a working brian2genn would ease the creation and execution of test suites.

Right now, we are using the following combination of repos (with slight modifications) -- thanks to Esin Yavuz for reporting the specific commits:
brian2: commit ac06993ac83101edf3fac3cec984f7ef161ea1a0
brian2genn: commit 5efbcc717dd6964e260aec3e60f28624eaa3c9d9
GeNN: commit 0621048c8ef0f081032f39303ce8846788bae9ef

**Comment by thesamovar** [comment]
This is actually intended for the moment. To keep development time down, we froze brian2genn on a particular commit of brian2, but it will be updated for the final release of brian2.

**Comment by moritzaugustin** [comment]
thanks. then we will proceed with the specific commits above for the comparison

**Comment by tnowotny** [comment]
The heads of brian2genn and brian2 were again matched up 3 days ago. But the match is guaranteed to break more often in the coming weeks.

**Comment by moritzaugustin** [comment]
thank you! but could you maybe refine your last post, i.e., which commits exactly (from the three repositories: brian2, genn, brian2genn) are supposed to be working for standard brian2 examples?

**Comment by tnowotny** [comment]
Brian2: d82e7a4419e61d262126a96dc1bed35e37bac761
brian2genn: e1e0b790088fbd40cb713baba2dfa062c9ada903
GeNN: f9ea2fe4aa73799e4242b1e8713733d7c2570478
(this configuration was tested 16 October and is working on the usual feature tests).

**Comment by moritzaugustin** [comment]
wow that was fast! have a nice weekend and thank you for the answer

**Comment by moritzaugustin** [comment]
i would like to know whether more recent brian2genn/genn/brian2 commits are considered to be working. could you tell again the respective commit hashes (for *genn: of the development branches)? 
thanks in advance and i wish you a merry christmas

**Comment by tnowotny** [comment]
Pretty much nothing has happened since I commented 16 Oct. - those versions are your best bet atm.

**Comment by tnowotny** [comment]
There is some problem with the brian2genn version cited above, so if interested in testing at this stage (15 Feb 2016) use:
Brian 2: 71f12749e24f1e5eb6c775c331d8ad5060daad95
brian2genn: a00d75961c9eb95fcbee5c05bbf8cc7602c86765
genn: 0cb5825cbc45ce3b2c4fc0c499c6377b8b31f3fd

**Comment by tnowotny** [comment]
Brian2Genn is now working with the latest Brian 2 and GeNN master branches.

**Comment by mstimberg** [comment]
> Brian2Genn is now working with the latest Brian 2 and GeNN master branches.

Since this is indeed the case, I'll close this issue.
