### ISSUE TITLE
Modulo operator with integer arguments cannot be used from GPU code

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2genn#43]
It is of course not a real-world use case in this form, but the following code fails with brian2genn on GPU (but not on CPU):
```Python
from brian2 import *
import brian2genn
set_device('genn')
group = NeuronGroup(100, '', threshold='i % 25 == 0')
run(1*second)
```
Error:
```
..../magicnetwork_model_CODE/neuronKrnl.cc(45) (col. 18): error: calling a __host__ function("std::fmod<int, int> ") from a __global__ function("calcNeurons") is not allowed
```

It works fine for floating point arguments.

**Comment by tnowotny** [comment]
This seems to suggest that brian2genn translates ```i % 25``` into ```fmod(i,25)``` where ```i``` and ```25``` are integers. CUDA libraries do not provide ```fmod``` for types ```int, int```.
Is there a particular reason why ```i % 25``` is not used as such but translated to use ```fmod```?
Solutions I can see: 
1 - use ```i % 25``` in the generated code
2 - introduce explicit casts: ```(int) fmod((float) i, (float) 25)```
The latter feels very awkward to me.

**Comment by mstimberg** [comment]
This is one of the annoying things of C (until C++11 at least), the `%` operator used to only work for integers while `fmod` only worked with floats. This still seems to be true on Windows and, as we see in this bug, for CUDA. The reason why we are not leaving things as they are is that in our current code generation pipeline, the "renderer" only sees `x % y` and does not know whether the two arguments are floats or integers. In Brian, we translate it therefore to `brian_mod(x, y)` and have various `brian_mod` implementation with different argument types, where the float variants delegate to `fmod` and the integer one to the `%` operator.
It actually does something more, it also changes the behaviour for negative numbers because `fmod` and Python's `%` operator differ in that regard (e.g. `fmod(-1, 10)` is -1 whereas `-1 % 10` (in Python, not in C) is 9). We follow the Python convention.

The easiest solution would be to copy Brian's approach and add the (quite ugly, but well...) `brian_mod` function to the support code, adding the `__host__ __device__` stuff. Actually, we should reduce the clutter a bit and not generate code for all these datatypes like `short` or `unsigned int` that we do not support anyway.

**Comment by tnowotny** [comment]
I agree, for the purposes of brian2genn it makes the most sense to copy the Brian2 approach. I suspect we need versions for 
```
int, int
float, float
double, double
```
I am not sure about mixed versions like ```float, int```?

**Comment by mstimberg** [comment]
In current Brian 2 master, we support a total of 13 data types and all 169 possibilities of combining them. In a (still unmerged) PR (brian-team/brian2#814) I propose to reduce this to 6 data types and 36 variants, but I think for brian2genn the 3 you mention should be enough. I think we do need the variants with mixed types (i.e. a total of 9 variants), because otherwise we'll run into the "call is ambiguous" error too easily.
So how about copying this code: https://github.com/brian-team/brian2/blob/ac983f23cece5558892be198d028e2b2f95b4feb/brian2/codegen/generators/cpp_generator.py#L91
adapted to just `int, float, double`?

**Comment by tnowotny** [comment]
sounds good to me.
on the issue of python versus C convention on negative numbers ... let's stick with what you've got even if I don't find it too intuitive.

**Comment by mstimberg** [comment]
I just realized there's another problem with this: each Brian `CodeObject` has its own support code, but in brian2genn we pass one single support code for the state update, threshold, and reset of a `NeuronGroup`. This will not work if the same function is defined in more than one of the object's support codes. With `_brian_mod` defined in the "universal support code", this will always be the case, but it just highlights a general problem; using the same "user-defined" (i.e. non-standard) function (`int` or `clip`) both in the reset and in the threshold, or both in the state updater and the reset will also raise an error at the current state of brian2genn.
I have an idea how to fix this in a relatively clean way, but this will have to be built on top of the fix for #41.

**Comment by tnowotny** [comment]
Hum ... you are right ... this is an issue. We have independently drifted into the opposite direction of doing a smaller number of support code scopes in GeNN than previously arguing that it seems unlikely that users would actually need two different functions with the same name in two code snippets that refer to the same neural network element (a neuron or a synapse). We need to see how we can bring things together ...

**Comment by mstimberg** [comment]
> doing a smaller number of support code scopes in GeNN than previously arguing that it seems unlikely that users would actually need two different functions with the same name in two code snippets that refer to the same neural network element (a neuron or a synapse).

Just to make this clear: it's not about two different functions with the same name (you cannot do this in Brian for stateupdate/threshold/reset), it's about using the *same* function in both snippets. In the current code, stateupdate/threshold and reset generate independent support code (since each is represented by a `CodeObject`) which is then simply glued together before passing it to GeNN. In the branch fixing the issue #41 I've now merged all three parts of a neural model into a single `CodeObject`, solving this issue.
