### ISSUE TITLE
Models with heteregoneous delays don't give warning or error?

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2genn#49]
When specifying heterogeneous delays in `brian2genn`, they are silently ignored. I know they are not supported, but shouldn't there be at least a warning or even an error?

[This old Brian2 example](http://brian2.readthedocs.io/en/2.0a8/examples/synapses.html) demonstrates this well when comparing the resulting plots when using `cpp_standalone` and `genn` device. Even though synapses with different delays are created, the simulation just uses no delay (or maybe just the first delay value?, didn't check that).
```python
from brian2 import *
import brian2genn

set_device('genn')
#set_device('cpp_standalone')

G1 = NeuronGroup(10, 'dv/dt = -v / (10*ms) : 1',
                threshold='v > 1',
                reset='v=0.')
G1.v = 1.2
G2 = NeuronGroup(10, 'dv/dt = -v / (10*ms) : 1',
                 threshold='v > 1',
                 reset='v=0')

syn = Synapses(G1, G2, 'dw/dt = -w / (50*ms): 1', pre='v+=w')

syn.connect('i == j', p=0.75)

# Set the delays
syn.delay[:] = '1*ms + i * ms + 0.25*randn()*ms'
# Set the initial values of the synaptic variable
syn.w[:] = 1

mon = StateMonitor(G2, 'v', record=True)
run(20*ms)
plot(mon.t / ms, mon.v.T)
show()
```

Note: I'm not using the latest brian2genn version, I'm on commit 0553cafeab49ea5403c0230411035df504d4db06, in case there were changes since then.

**Comment by mstimberg** [comment]
Ah, thanks, that's indeed a bug. I added a somewhat indirect check for heterogeneous delays in commit ac3a201 but this only checks for assignments with concrete values. For some reason, I forgot about string-based assignments... I will fix this soon.
