### ISSUE TITLE
gcc bug making "isnan" ambiguous

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#54]
(https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60407)
This affects us in the ```b2glib/convert_synapses.h``` codes.
A simple solution is to explicitly call ```std::isnan``` instead of ```isnan```.
I have done this in the fix_isnan branch.
@mstimberg, What do you think?

**Comment by mstimberg** [comment]
Fix looked good to me --> merged.

Fixed via 9a1a975
