### ISSUE TITLE
Are unsupport features of the version1.1.5 the same as the earlier version?

### ISSUE THREAD

**Issue by alicesue** [brian-team/brian2genn#56]
I want to use brain2genn to establish multi-networks and multi-synapse. I solwant to ask that if the version1.1.5  has solved the problem? Thank you!

**Comment by tnowotny** [comment]
I don't think there have been any changes on these, unless @mstimberg has been busy secretly. I would note, however, that depending on what you want to do, there are simple workarounds. E.g. the populations in a "network" need not necessarily be connected, so you can easily define multiple functional networks within the same "network".

**Comment by mstimberg** [comment]
Version 1.1.5 is basically identical to version 1.0, apart from "boring" fixes for packaging, testing etc. As Thomas said, those restrictions should not necessarily matter, in particular I don't know of any real-world use cases for multiple networks (in the sense mentioned in the known restrictions) within a simulation.
Oh, and feel free to ask questions like this on the Brian mailing list (briansupport@googlegroups.com https://groups.google.com/group/briansupport) -- we should mention it somewhere in the brian2genn docs...
