### ISSUE TITLE
Default linker flags broke compilation

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#59]
Hi @mstimberg, at Capocaccia we had a participant who wanted to try brian2genn on Windows and he was unable to compile because in makefile_common_win.mk from the included GeNN version, ```LINK_FLAGS``` were added to rather than replaced. As a result they contained a strange default of "-MD" and something else which I can't recall. The "-MD" forced cl to do some kind of dynamic linking while nvcc (by default) seems to do some static linking that is the equivalent of what cl would do with a "-MT" flag. Linking then failed with an error message that dynamically linked and statically linked object files can't be linked together. When we replaced ```LINK_FLAGS``` rather than adding to it, everything seemed to work. I wonder whether we should make the effort to patch the GeNN version you packaged into brian2genn (or at this time update to something more recent) and repackage brian2genn and release  to fix this problem? Relatedly, I am wondering whether you tested brian2genn on Windows with a GPU? Because I am not sure whether this is a problem with this guy's particular setup or whether it is a general problem (it wouldn't appear in the CPU_ONLY version as you wouldn't link cl compiled obj files and nvcc compiled ones).

**Comment by thesamovar** [comment]
Happy to test it on Windows if that would be useful. Any particular choices about versions of everything?

**Comment by mstimberg** [comment]
If I understood correctly, the participant used the GeNN version that comes with Brian2GeNN. That means to test you should install the brian2genn conda package (`conda install -c brian-team brian2genn`) and run a simulation with it (to make sure it uses the pre-packaged GeNN, you can unset `GENN_PATH` if it is set on your system).

**Comment by thesamovar** [comment]
Do I need a particular version of CUDA tools?

**Comment by mstimberg** [comment]
I don't think Brian2GeNN/GeNN depends on any particular version, but your Visual Studio version might restrict the compatible choices I think (at least that's the case for gcc on Linux).

**Comment by thesamovar** [comment]
Is there a standard test script?

**Comment by mstimberg** [comment]
The issue should appear with any example, but for the full test suite you can run `scripts/run_brian_tests.py`

**Comment by mstimberg** [comment]
This issue seems to be different from the one Thomas was reporting, it seems our package pre-compiled stuff with Visual Studio 2013 and you are using Visual Studio 2015... We'll need to do something about this in any case, at least display a warning telling users to install GeNN manually. We could create packages for various VS versions, but given that VS is not installed via anaconda, I don't know how we could provide these packages in a nice way.

**Comment by thesamovar** [comment]
I think VS is now installed via anaconda. Output of ``conda list``:

```
# packages in environment at C:\Anaconda\envs\testbrian2genn:
#
brian2                    2.1.2               np113py27_0    brian-team
brian2genn                1.1.5            py27h45f29f9_0    brian-team
certifi                   2018.4.16                py27_0  
cython                    0.28.2           py27h0c8e037_0  
fastcache                 1.0.2            py27h0c8e037_2  
gsl                       2.2.1                     vc9_2  [vc9]  brian-team
icc_rt                    2017.0.4             h97af966_0  
intel-openmp              2018.0.0                      8  
jinja2                    2.10             py27hba1794b_0  
markupsafe                1.0              py27h9d4480d_1  
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py27hc997a72_0  
mpmath                    1.0.0            py27h0d59bc2_2  
numpy                     1.13.3           py27h0bb1d87_4  
pip                       10.0.1                   py27_0  
py-cpuinfo                3.2.0                    py27_0    brian-team
pyparsing                 2.2.0            py27hc7d9fa6_1  
python                    2.7.15               he216670_0  
scipy                     1.1.0            py27ha6b90e7_0  
setuptools                39.1.0                   py27_0  
sympy                     1.1.1            py27hde44fae_0  
vc                        9                    h7299396_1  
vs2008_runtime            9.00.30729.1         hfaea7d5_1  
vs2008_win-64             9.00.30729.1         hb7fc0b5_1  
weave                     0.15.0                   py27_0    brian-team
wheel                     0.31.0                   py27_0  
wincertstore              0.2              py27hf04cefb_0  
```

I assume ``vs2008_win-64`` is Visual Studio 2008? As well as this, I have VS 2008, VS 2010 and VS 2013 installed but not 2015 I think. But it should be using the environment variables for VS 2008.

If I pip install instead of conda install would that work do you think?

**Comment by thesamovar** [comment]
Doing ``conda install vs2015_win-64`` doesn't remove ``vs2008``, it works fine, but the same error on running ``simple_example.py``.

**Comment by mstimberg** [comment]
Hmm, I looked into this in a bit more detail and I don't yet know what the best solution is. I think all that `vs2015_win-64` and equivalent packages do is to run `vcvarsall.bat` (you need to deactivate and activate the environment to see this -- annoyingly, it closes the terminal window if an error occurs, e.g. it cannot find the compiler...). Now for brian2genn all this does not really matter, as we'll explicitly run `vcvarsall.bat` ourselves after searching for the latest available version. Maybe we should make this optional? Or only do it when it hasn't been run already (I guess there's an environment variable we can check)?
In your case, just for testing whether it works at all or whether you get the error reported by Thomas, can you explicitly set the `codegen.cpp.msvc_vars_location` preference in the `simple_example` script to the path of your VS 2015 installation?

**Comment by thesamovar** [comment]
I don't have VS 2015 - will see if I can install it.

**Comment by mstimberg** [comment]
Oh, one more thing. I now realized that the `vs..._win-64` packages that are required by our `brian2genn` package are the ones that are required for building Python extensions. So when you install Brian2/Brian2GeNN this way with Python 2, you'll get the package for VS 2008... I guess this means we shouldn't use these kind of packages to determine/fix the compiler that is used for standalone/GeNN (you cannot use the latest CUDA version with VS 2008 for example).

**Comment by thesamovar** [comment]
Yes good point since we're not building Python extensions. So is the take-home message at the moment that the anaconda distribution depends on having VS 2015 installed because we have some precompiled binaries for that version? VS 2015 installing now so we'll see!

**Comment by mstimberg** [comment]
> So is the take-home message at the moment that the anaconda distribution depends on having VS 2015 installed because we have some precompiled binaries for that version?

Yes, the reason that we need to pre-compile things in the first place is that during GeNN's code generation process, a few files are compiled within the GeNN source directory itself -- potentially the user is not allowed to compile files there (system-wide instead of user installation) and in general I think we are not supposed to add new files into Anaconda directories after installation (e.g. they would not be removed during an uninstall). I guess in the long run GeNN could be restructured in a way that the files are rather copied into the user project or something like that?

**Comment by thesamovar** [comment]
Still problems - apparently my version of CUDA toolkit is too old for MSVC 2015! Will update that tomorrow.

**Comment by tnowotny** [comment]
Hi guys ... just saw this has kicked off today ... it's a typical Windows build experience, isn't it (sorry, Dan). As for restructuring GeNN to not write into its own install location ... we need to think about this. In this context I can see it makes a lot of sense but the compilation of the GeNN library file in place makes a lot of sense in our GeNN context (I thought). What do you think @neworderofjamie?

**Comment by neworderofjamie** [comment]
Damn...a lot of Windows build issues definitely crawled out when we lifted that stone!

GeNN being checked out somewhere read only to the user (i.e. system site packages) is indeed not something that really makes sense when using it in a standalone way. However I don't think it would be that difficult to modify the build system to allow it. The Windows build system actually allows this already so, for instance, to build libgenn with the intermediate files and library being written to a random folder on your (/my) desktop you could do the following:

``
msbuild /p:Configuration=Release_CPU_ONLY /p:IntDir=c:\Users\newor\Desktop\test\obj\ /p:OutDir=c:\Users\newor\Desktop\test\lib\ lib_genn.vcxproj
``

The Linux/Mac build system would need a little more work and the ``genn-buildmodel`` scripts etc would need updating to pass the output directory through but it would definitely be possible!

**Comment by tnowotny** [comment]
I *think* this has been resolved with the GeNN 4 changes and the corresponding brian2genn updates in #101
