### ISSUE TITLE
Wrong number output format during code generation?

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#62]
I just found this in generated code:
```#define SCALAR_MAX 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000```
I think this is not sensible (if C++ even understands it) - the constant should have appeared in a floating point notation.

**Comment by mstimberg** [comment]
I think this is generated in GeNN, not in Brian2GeNN:
```C++
    os << "#define SCALAR_MAX " << SCLR_MAX << std::endl;
```
https://github.com/genn-team/genn/blob/161dadf11985e39f4e13c8a67c4374496f693d01/lib/src/generateRunner.cc#L463

**Comment by tnowotny** [comment]
Well spotted, now issue #194 in genn-team/genn.
