### ISSUE TITLE
Support single precision

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2genn#69]
See discussion in brian-team/brian2#981 (currently needs Brian2 from master branch).

**Comment by neworderofjamie** [comment]
Hah good idea - sorry for confusing the issue!

Unless you have any strong objections my plan is, in the short term, to add support for double-precision time to GeNN and, in the longer term, I'll remove the transcendental function name mangling along with a lot of essentially legacy stuff meaning that you'll have much more control over precision.

**Comment by tnowotny** [comment]
I think this is a good plan. After phase one (introducing the independent precision control for ```t```) we can adjust Brian2genn and finally get to benchmarking.
Remains the question about a version info functionality for GeNN ...

**Comment by tnowotny** [comment]
I assume we will then have to do the logic in a away that has GeNN version < XXX if the version.txt does not exist and otherwise its content ... don't think it is possible to introduce retrospectively into earlier versions ...

**Comment by neworderofjamie** [comment]
@mstimberg - does https://github.com/genn-team/genn/pull/206 work for you?

**Comment by mstimberg** [comment]
@neworderofjamie : yes looking good to me
@tnowotny : yes, not having it for older versions is perfectly fine

**Comment by tnowotny** [comment]
@mstimberg , once we have merged https://github.com/genn-team/genn/pull/207 we should be ready to enable float32 support for brian2genn. Just needs inserting the setTimePrecision command if the GeNN used is new enough to have it.

**Comment by mstimberg** [comment]
Great, I'll take care of this tomorrow.

**Comment by mstimberg** [comment]
@tnowotny , @neworderofjamie Which version should we require for this feature? Current `version.txt` still says 3.1.1, but that release did not yet contain the feature. Should we require `3.1.2` or will the next release be `3.2`?

**Comment by neworderofjamie** [comment]
The next release (coming soon) will indeed be 3.2.0

**Comment by denisalevi** [comment]
When do you expect single precision to be available in the brian2genn? I guess it depends on the GeNN 3.2 release?
We will start running final benchmarks on Friday. If single precision is available by then, we would be happy to include it.

**Comment by mstimberg** [comment]
I just opened PR #72 which removes the need to wait for GeNN 3.2 -- it just raises a warning for now, we can change this into an error as soon as GeNN 3.2 is released.

**Comment by tnowotny** [comment]
being lazy I will ask and not inspect the code: What happens of one tries to use the single precision brian2genn with an older GeNN version before the ```setTimePrecision``` function was introduced? I suspect it crashes during compilation?

**Comment by mstimberg** [comment]
Yes, unfortunately it will raise a warning and then crash... Maybe it would be cleaner to say something about the GeNN version in the error message you get for the failed compilation?

**Comment by tnowotny** [comment]
on the other hand it could have crashed during compilation for many different reasons ... on second thought, I think it is fine with warning + crash as you have it for now. Once GeNN 3.2. is released we change it to an error and everything is clean.
