### ISSUE TITLE
reset_device() and run() results in 'Only a single run statement is supported'

### ISSUE THREAD

**Issue by JustasB** [brian-team/brian2genn#76]
In [Multiple Runs](https://brian2genn.readthedocs.io/en/latest/introduction/exclusions.html#multiple-runs) section in documentation it states that:

> code can be run repeatedly “in multiple runs” that are completely independent. This just needs a reset_device command issued after the run(runtime) command

However, I get a the 'Only a single run statement is supported' error when I try to run() after device_reset()

Smallest code to reproduce the error:

```
from brian2 import *                   
import brian2genn   
set_device('genn')
run(1*second)

from brian2.devices import reset_device
reset_device('genn')

run(1*second) # <- results in above error
```

**Comment by mstimberg** [comment]
Hi,
thanks, that's indeed incorrect/outdated in the documentation. The correct way is to use `device.reinit()` and `device.activate()` as described for the C++ standalone mode in Brian2 : https://brian2.readthedocs.io/en/stable/user/computation.html#multiple-builds

I.e., the following should work for Brian2GeNN as well:
```Python
from brian2 import *
import brian2genn
set_device('genn')
run(1*second)

device.reinit()
device.activate()

run(1*second)
```

**Comment by JustasB** [comment]
@mstimberg Thank you, it's working. Also, thank you for updating the docs.
