### ISSUE TITLE
Random numbers and stochastic differential equations

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2genn#8]
There is an issue about seeding RNGs correctly.

**Comment by tnowotny** [comment]
Random number generators rand() and randn() are now working as expected I believe. Subject to more testing.
BinomialFunction could also be done but I am unsure about where to put the code. So far BinomialFunction is defined in brian2.input.binomial. If I just ad the genn implementation there alongside the other implementations (in the BinomialFunction.__init__ function) that would work but introduce a dependency of Brian2 on Brian2GeNN. That's probably not what we want. But how else to add the genn implementation?

**Comment by mstimberg** [comment]
I don't see any good way to make this work at the moment, unfortunately. I filed an issue for it, it should only need a bit of refactoring in Brian2 : brian-team/brian2#542.

As a short term solution you could add a `GeNNBinomialFunction` class, but of course that will not be automatically used by `PoissonInput`. But then again, `PoissonInput` is just a convenience wrapper around creating a binomial function object and calling a `run_regularly` operation on the group with `target_var += binomial()*weight`.

**Comment by tnowotny** [comment]
If BinomialFunction implementations were hanging around in something like DEFAULT_FUNCTIONS then it would be very easy.

**Comment by mstimberg** [comment]
The problem is that there's not one implementation as for other functions. You use `BinomialFunction` like:
```Python
binomial = BinomialFunction(n=1000, p=0.01)
G = NeuronGroup(...)
G.run_regularly('v += binomial()*0.1')
```
From Brian's point of view, each `BinomialFunction` instance will be a separate function with separate implementation. But it's not terribly complicated, after the refactoring for brian-team/brian2#542 you'll have to do something like:
```Python
def genn_code_for_binomial(n, p, use_approximation=True):
    # ...

BinomialFunction.code_generators[GeNNCodeObject] = genn_code_for_binomial
```

**Comment by tnowotny** [comment]
Oh - I see: The different n and p. What you propose sounds like a good plan. I will have the code ready once this is done.

**Comment by tnowotny** [comment]
Binomial function now working I believe. Moving on.
