### ISSUE TITLE
NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run.

### ISSUE THREAD

**Issue by liftaylor** [brian-team/brian2genn#89]
Hi, I was running a STDP network and it ended up with this NotImplementedError. My Brian2Genn is 1.31, GENN is 3.3.0, and CUDA is 10.1. I am using the latest Brian2 package on Python 2.7. 

        "raise NotImplementedError('Cannot retrieve the values of state '
        NotImplementedError: Cannot retrieve the values of state variables in standalone code before the 
        simulation has been run."

If you need my code snippet, I will paste it here later. Thanks

By the way, this is my first time to use Brian2Genn, and my current code takes 6 days to run on a 16 core Xeon CPU, and 32 GB RAM machine. I am curious what the performance improvement will be like if I use CUDA with Brian2Genn, and my graphic card is NVidia 1060 6GB RAM.

**Comment by mstimberg** [comment]
The error message means that you are trying to access the value of state variables (or e.g. indices of synapses), before running the simulation. Note that in Brian2GeNN (and e.g. C++ standalone mode), everything that you write until the final `run` has not been executed yet. Therefore, if you ask for example for the indices of synapses, Brian2GeNN cannot know them because it has not actually created the synapses yet. To be more specific, we'd have to know which line raises this error (and potentially some more context from your code).



> By the way, this is my first time to use Brian2Genn, and my current code takes 6 days to run on a 16 core Xeon CPU, and 32 GB RAM machine. I am curious what the performance improvement will be like if I use CUDA with Brian2Genn, and my graphic card is NVidia 1060 6GB RAM.

It is hard to say, it strongly depends on your model. In the worst case it might change nothing at all, in the best case it can run 50x times faster, all depends on the number of neurons and synapses, the details of the neuron and synapses models, etc. 

Maybe our Brian2GeNN preprint on biorxiv might give you some general idea: https://www.biorxiv.org/content/10.1101/448050v1

**Comment by liftaylor** [comment]
Thank you so much for the feedback. Below is part of the code, the problem happens at the line that is bold.

`# ------------------------------------------------------------------------------
# create network population and recurrent connections
# ------------------------------------------------------------------------------
for subgroup_n, name in enumerate(population_names):
    print 'create neuron group', name
    neuron_groups[name + 'e'] = neuron_groups['e'][subgroup_n * n_e:(subgroup_n + 1) * n_e]
    neuron_groups[name + 'i'] = neuron_groups['i'][subgroup_n * n_i:(subgroup_n + 1) * n_e]
    neuron_groups[name + 'e'].v = v_rest_e - 40. * mV
    neuron_groups[name + 'i'].v = v_rest_i - 40. * mV

    if test_mode or weight_path[-8:] == 'weights/':
        neuron_groups['e'].theta = np.load(weight_path + 'theta_' + name + ending + '.npy') * volt
    else:
        neuron_groups['e'].theta = np.ones((n_e)) * 20.0 * mV

    print 'create recurrent connections'
    for conn_type in recurrent_conn_names:
        connName = name + conn_type[0] + name + conn_type[1]
        weightMatrix = get_matrix_from_file(weight_path + '../random/' + connName + ending + '.npy')
        model = 'w : 1'
        pre = 'g%s_post += w' % conn_type[0]
        post = ''
        if ee_STDP_on:
            if 'ee' in recurrent_conn_names:
                model += eqs_stdp_ee
                pre += '; ' + eqs_stdp_pre_ee
                post = eqs_stdp_post_ee
        connections[connName] = Synapses(neuron_groups[connName[0:2]], neuron_groups[connName[2:4]], model=model, on_pre=pre, on_post=post)
        connections[connName].connect(True)  # all-to-all connection
        **connections[connName].w = weightMatrix[connections[connName].i, connections[connName].j]**

    print 'create monitors for', name
    rate_monitors[name + 'e'] = PopulationRateMonitor(neuron_groups[name + 'e'])
    rate_monitors[name + 'i'] = PopulationRateMonitor(neuron_groups[name + 'i'])
    spike_counters[name + 'e'] = SpikeMonitor(neuron_groups[name + 'e'])

    if record_spikes:
        spike_monitors[name + 'e'] = SpikeMonitor(neuron_groups[name + 'e'])
        spike_monitors[name + 'i'] = SpikeMonitor(neuron_groups[name + 'i'])

# ------------------------------------------------------------------------------
# create input population and connections from input populations
# ------------------------------------------------------------------------------
pop_values = [0, 0, 0]
for i, name in enumerate(input_population_names):
    input_groups[name + 'e'] = PoissonGroup(n_input, 0 * Hz)
    rate_monitors[name + 'e'] = PopulationRateMonitor(input_groups[name + 'e'])

for name in input_connection_names:
    print 'create connections between', name[0], 'and', name[1]
    for connType in input_conn_names:
        connName = name[0] + connType[0] + name[1] + connType[1]
        weightMatrix = get_matrix_from_file(weight_path + connName + ending + '.npy')
        model = 'w : 1'
        pre = 'g%s_post += w' % connType[0]
        post = ''
        if ee_STDP_on:
            print 'create STDP for connection', name[0] + 'e' + name[1] + 'e'
            model += eqs_stdp_ee
            pre += '; ' + eqs_stdp_pre_ee
            post = eqs_stdp_post_ee

        connections[connName] = Synapses(input_groups[connName[0:2]], neuron_groups[connName[2:4]],
                                            model=model, on_pre=pre, on_post=post)
        minDelay = delay[connType][0]
        maxDelay = delay[connType][1]
        deltaDelay = maxDelay - minDelay
        # TODO: test this
        connections[connName].connect(True)  # all-to-all connection
        connections[connName].delay = 'minDelay + rand() * deltaDelay'
        connections[connName].w = weightMatrix[connections[connName].i, connections[connName].j]

# ------------------------------------------------------------------------------
# run the simulation and set inputs
# ------------------------------------------------------------------------------
now = datetime.datetime.now()
print 'simulation started at ',str(now)
net = Network()
for obj_list in [neuron_groups, input_groups, connections, rate_monitors,
                 spike_monitors, spike_counters]:
    for key in obj_list:
        net.add(obj_list[key])`

**Comment by tnowotny** [comment]
I think it is exactly as @mstimberg has explained above. Accessing variable values before the run is for principal reasons not possible in brian2genn. I will close this issue for now; do reopen if there is more to discuss.
