### ISSUE TITLE
Brian test is failing with too few arguments for _binomial_2 and _binomial_3

### ISSUE THREAD

**Issue by tnowotny** [brian-team/brian2genn#93]
Hi @mstimberg , I was trying to look into the issues we had with benchmarking and was going through a few things when I noticed that the Brian tests didn't seem to run through.
I am a bit clumsy with this stuff, so was not quite sure how I find out which test it is that is failing. But the failure essentially boils down to that code is generated in the neuronFnct or neuronKrnl that calls the support_code functions _binomial_2 and _binomial_3 without arguments whereas those functions are expecting a seed argument of type int64_t.
Have you come across this before?
I am using manual check-outs for brian2 and brian2genn, both at the latest master.

**Comment by mstimberg** [comment]
Oh, I'm sorry about that, this is due to the changes in brian-team/brian2#1111.
I actually already have a fix, but it was written on top of the changes in #92 , so I wanted to wait until that one got merged. Maybe we should just do that now? I was waiting for a confirmation that the fix is ok, but everything worked correctly for me at least.

**Comment by tnowotny** [comment]
Yes, I am not sure we can wait for @schlowm0 to approve the pull request ... so probably ok to merge it now and hope it is ok.

**Comment by tnowotny** [comment]
Hi @mstimberg ... I am still getting the original test failures as described above ... is there still another issue here?

**Comment by tnowotny** [comment]
Ah ... and scrolling through the entire trace of error output, not surprisingly the test that is failing is actually called ```brian2.tests.test_functions.test_binomial```

**Comment by mstimberg** [comment]
That PR (#94) isn't merged yet, or do you mean that you still get the errors when you check out the `fix_vectorisation_idx` branch?

**Comment by tnowotny** [comment]
oh, sorry ... I jumped the gun there. I didn't realise it wasn't merged yet.

**Comment by schlowm0** [comment]
Sorry guys I recently switched labs and I'm still in the process of setting up
