### ISSUE TITLE
Issues with interfacing Brian2 with GeNN

### ISSUE THREAD

**Issue by Ahish-aeon** [brian-team/brian2genn#98]
Hello All,

I have been trying to run a simple brain2 code on GPU using GeNN. However, there are some issues with that. Please help resolve this issue and use GPU capabilities for simulating SNN. I have attached the error files and brain2code, stdout and stderr files were empty. Hope to hear soon. Thank you!

[Brian2Cuda.txt](https://github.com/brian-team/brian2/files/3907626/Brian2Cuda.txt)
[Error_Brian2GeNN.txt](https://github.com/brian-team/brian2/files/3907624/Error_Brian2GeNN.txt)
[Error_log1.txt](https://github.com/brian-team/brian2/files/3907625/Error_log1.txt)

**Comment by mstimberg** [comment]
Hi. As stated in [GeNN's installation instructions](https://genn-team.github.io/genn/documentation/3/html/d8/d99/Installation.html), you'll have to set the `GENN_PATH` and `CUDA_PATH` environment variables to the respective directories. From your log, it seems that you have instead set them to a *list* of paths. Guessing from the entries in these lists, try using the following settings:
```
GENN_PATH=/home/ahish/SNN_MNIST/Brian2GeNN/genn
CUDA_PATH=/usr/local/cuda-10.0
```

**Comment by Ahish-aeon** [comment]
Hi Dr. Marcel,
Thank you for your quick reply. I did change the paths and still facing issues with the interfacing. Please find the logfile and brain code attached to this email. Kindly let me know what's going wrong. Hope to hear from you soon. Thank you for your support!
[brian_debug_oxJfvc.log](https://github.com/brian-team/brian2genn/files/3912787/brian_debug_oxJfvc.log)
[brian_debug_oxJfvc.txt](https://github.com/brian-team/brian2genn/files/3912788/brian_debug_oxJfvc.txt)
[error.txt](https://github.com/brian-team/brian2genn/files/3912789/error.txt)
[genn_trial1.txt](https://github.com/brian-team/brian2genn/files/3912790/genn_trial1.txt)

**Comment by mstimberg** [comment]
Ah, I see you are using GeNN 4.x. This version did not exist yet when Brian2GeNN was last released, and they are not compatible at the moment. Please install GeNN 3.x instead.

**Comment by Ahish-aeon** [comment]
Thank you for the support Dr. Marcel, 

I have been using multiple runs in my code, GeNN builds the model every run. This actually slows down the simulation. Kindly let me know if you have any workarounds for this. Thanks again!

**Comment by mstimberg** [comment]
Closing this issue since the original problem was about using GeNN 4 which is now supported via #101 .

Sorry about never replying to the last comment: running several builds is indeed slow with Brian2GeNN, there's currently no way to avoid it except for avoiding multiple runs in the first place. Sometimes this is possible e.g. by using a `run_regularly` function that sets/resets variables after a certain time.
